apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.project_slug}}-backend-test
  labels:
    app: {{cookiecutter.project_slug}}-backend-test
spec:
  type: NodePort
  selector:
    app: {{cookiecutter.project_slug}}-backend-test
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32121
---
apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.project_slug}}-frontend-test
  labels:
    app: {{cookiecutter.project_slug}}-frontend-test
spec:
  type: NodePort
  selector:
    app: {{cookiecutter.project_slug}}-frontend-test
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 32122
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{cookiecutter.project_slug}}-backend-test
  labels:
    app: {{cookiecutter.project_slug}}-backend-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{cookiecutter.project_slug}}-backend-test
  template:
    metadata:
      labels:
        app: {{cookiecutter.project_slug}}-backend-test
    spec:
  
      nodeSelector:
        dedicated: master
      tolerations:
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule

      imagePullSecrets:
      - name: regcred
      containers:
        - image: sasoldevchemicalsdigitalreg.azurecr.io/{{cookiecutter.project_slug}}-backend:test
          name: {{cookiecutter.project_slug}}-backend-test
          command: ["/app/entrypoint.sh"]
          args: ["gunicorn", "yet.wsgi:application", "--bind", "0.0.0.0:8000"]
          imagePullPolicy: IfNotPresent

    
          envFrom:
          - secretRef:
              name: {{cookiecutter.project_slug}}-test-secret

          ports:
            - containerPort: 8000
              name: gunicorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{cookiecutter.project_slug}}-frontend-test
  labels:
    app: {{cookiecutter.project_slug}}-frontend-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{cookiecutter.project_slug}}-frontend-test
  template:
    metadata:
      labels:
        app: {{cookiecutter.project_slug}}-frontend-test
    spec:
  
      nodeSelector:
        dedicated: master
      tolerations:
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule

      imagePullSecrets:
      - name: regcred
      containers:
        - image: sasoldevchemicalsdigitalreg.azurecr.io/{{cookiecutter.project_slug}}-frontend:test
          name: {{cookiecutter.project_slug}}-frontend-test
          command: ["nginx"]
          args: ["-g", "daemon off;"]
          imagePullPolicy: IfNotPresent
    

          ports:
            - containerPort: 80
              name: nginx
